Feature/hocs 3559 update foi topics
UKHomeOffice/hocs-frontend pull request #727
Opened 2021-08-13 16:47 UTC by abarker66

The FOI Topics list now uses the full active DCU topics list via a type-ahead component.

2021-08-17 12:19 UTC, LaurieBennett requested changes
One logger to remove possibly

2021-08-17 14:00 UTC, abarker66 commented on server/lists/adapters/topicsfoi.js
> +    logger.debug('FOI_TOPICS', { topics: data.length });
Laurie, this is intentional - all/most the adapters log the data length to show the list size.

2021-08-17 14:56 UTC, gary-newbolt approved these changes
lgtm

2021-08-18 09:11 UTC, LaurieBennett approved these changes
All looks fine, pass

2021-08-18 09:11 UTC, LaurieBennett commented on server/lists/adapters/topicsfoi.js
> +    logger.debug('FOI_TOPICS', { topics: data.length });
Ah, that's fine then

2021-08-18 09:12 UTC, merged